= Contacts API


=== Find contacts
'''
Example how to find contacts by ids, contact list, Limit and Offset value.
[source]
    CallfireClient Client = new CallfireClient("api_login", "api_password");
    var request = new FindContactsRequest
    {
        Number = new List<string> { "16506190257", "18778973473" },
        Id = new List<long> { 1, 2 },
        Limit = 1,
        Offset = 0
    };
    Page<Contact> contacts = Client.ContactsApi.Find(request);
    Console.WriteLine(String.Join(",", contacts));

=== Get contact
'''
Example how to get contact by id. Deleted contacts can still be retrieved but will be marked deleted
 and will not show up when quering contacts via UI.
[source]
    CallfireClient Client = new CallfireClient("api_login", "api_password");
    Contact contact = Client.ContactsApi.Get(463633187003);

=== Create contact
'''
Example how to create contacts in the CallFire system. These contacts are not validated on creation.
 They will be validated upon being added to a campaign. Example how to create contact with custom fields.
[source]
    CallfireClient Client = new CallfireClient("api_login", "api_password");
    var contact = new Contact
    {
        HomePhone = "16505044730",
        FirstName = "John",
        LastName = "Doe",
        Properties = new Dictionary<string, string> { { "age", "30" }, { "customFieldN", "customValue" } }
    };
    IList<ResourceId> contacts = Client.ContactsApi.Create(new List<Contact> { contact });
    Console.WriteLine(String.Join(",", contacts));

=== Update contact
'''
Example how to update contact.
[source]
    CallfireClient Client = new CallfireClient("api_login", "api_password");
    var contact = new Contact
    {
        Id = 463633187003,
        HomePhone = "16505044730"
    };
    Client.ContactsApi.Update(contact);

=== Delete contact
'''
Example how to delete contact by id. This does not actually delete the contact, it just removes the contact from
 any contact lists and marks the contact as deleted so won't show up in queries anymore.
[source]
    CallfireClient Client = new CallfireClient("api_login", "api_password");
    Client.ContactsApi.Delete(463633187003);
