= DNC lists API


=== Find dnc lists
'''
Example how to find all do not contact (DNC) lists.
[source]
    CallfireClient Client = new CallfireClient("api_login", "api_password");
    var findRequest = new FindDncListsRequest();
    Page<DncList> doNotCallLists = Client.DncListsApi.Find(findRequest);
    Console.WriteLine("Page of dnc lists:" + doNotCallLists);

=== Create dnc list
'''
Example how to create do not contact (DNC) list.
[source]
    CallfireClient Client = new CallfireClient("api_login", "api_password");
    DncList dncList = new DncList { Name = "dncList1" };
    ResourceId dncListId = Client.DncListsApi.Create(dncList);

=== Get universal dnc numbers
'''
Example how to search Universal Do Not Contact by number.
[source]
    CallfireClient Client = new CallfireClient("api_login", "api_password");
    IList<UniversalDnc> universalDncNumbers = Client.DncListsApi.GetUniversalDncNumber("16502572135", "16502572136");

=== Get dnc list
'''
Example how to get DNC list by id.
[source]
    CallfireClient Client = new CallfireClient("api_login", "api_password");
    DncList dncList = Client.DncListsApi.Get(1975140003);

=== Delete dnc list
'''
Example how to delete DNC list.
[source]
    CallfireClient Client = new CallfireClient("api_login", "api_password");
    Client.DncListsApi.Delete(1975140003);

=== Get dnc list items
'''
Example how to get fifth 2 DNC items from list.
[source]
    CallfireClient Client = new CallfireClient("api_login", "api_password");
    GetByIdRequest getItemsRequest = new GetByIdRequest
    {
        Id = 1975140003,
        Limit = 2,
        Offset = 5
    };
    Page<DoNotContact> dncListItems = Client.DncListsApi.GetListItems(getItemsRequest);

=== Add dnc list item
'''
Example how to add 3 DNC items to list.
[source]
    CallfireClient Client = new CallfireClient("api_login", "api_password");
    DoNotContact dnc1 = new DoNotContact { Number = "12135543211", Text = true, Call = false };
    DoNotContact dnc2 = new DoNotContact { Number = "12135543212", Text = true, Call = false };
    DoNotContact dnc3 = new DoNotContact { Number = "12135543213", Text = true, Call = false };
    AddDncListItemsRequest<DoNotContact> addItemsRequest = new AddDncListItemsRequest<DoNotContact>
    {
        ContactListId = 1975140003,
        Contacts = new List<DoNotContact> { dnc1, dnc2, dnc3 }
    };
    Client.DncListsApi.AddListItems(addItemsRequest);

=== Remove dnc list item
'''
Example how to delete DNC list item (you should specify list id and phone number to delete).
[source]
    //number param is required
    CallfireClient Client = new CallfireClient("api_login", "api_password");
    Client.DncListsApi.RemoveListItem(1975140003, "16505044730");

=== Remove dnc list items
'''
Example how to delete DNC list items (you should specify list id and phone numbers to delete).
[source]
    //numbers param is required
    CallfireClient Client = new CallfireClient("api_login", "api_password");
    Client.DncListsApi.RemoveListItems(1975140003, new List<string> { "16505044730", "16505044731" });
