= Calls API

=== Find calls
'''
Example how to find all calls sent or received by the user. Use "CampaignId=0" for the campaignId parameter to query for all
 calls sent through the POST /calls API.
[source]
    CallfireClient Client = new CallfireClient("api_login", "api_password");
    //No one parameter is required
    var request = new FindCallsRequest
    {
        States = new List<StateType> { StateType.FINISHED, StateType.READY },
        IntervalBegin = DateTime.UtcNow.AddMonths(-2),
        IntervalEnd = DateTime.UtcNow,
        Limit = 3
    };
    Page<Call> calls = Client.CallsApi.Find(request);
    Console.WriteLine("Calls: " + calls);

=== Send call
'''
Example how to use the /calls API to quickly send individual calls via default campaign. A verified Caller ID and
 sufficient credits are required to make a call.
[source]
    CallfireClient Client = new CallfireClient("api_login", "api_password");
    //Only "recipients" param required
    var recipient1 = new CallRecipient { ContactId = 463633187003, LiveMessage = "testMessage" };
    var recipient2 = new CallRecipient { ContactId = 463633187003, LiveMessage = "testMessage" };
    var recipients = new List<CallRecipient> { recipient1, recipient2 };
    IList<Call> calls = Client.CallsApi.Send(recipients, null, "items(id,fromNumber,state)");
    Console.WriteLine("Calls: " + calls);

In case you want to send call via existing campaign provide campaign id as second parameter for send() method,
 see example below.
[source]
    CallfireClient Client = new CallfireClient("api_login", "api_password");
    //Only "recipients" param required
    var recipient1 = new CallRecipient { ContactId = 463633187003, LiveMessage = "testMessage" };
    var recipient2 = new CallRecipient { ContactId = 463633187003, LiveMessage = "testMessage" };
    var recipients = new List<CallRecipient> { recipient1, recipient2 };
    IList<Call> calls = Client.CallsApi.Send(recipients, 60000000003);
    Console.WriteLine("Calls: " + calls);

=== Get call
'''
Example how to return a single Call instance for a given call id.
[source]
    //Only "id" param required
    CallfireClient Client = new CallfireClient("api_login", "api_password");
    Call call = Client.CallsApi.Get(617067920003, "id,toNumber,state");
    Console.WriteLine("Call: " + call);
