= Calls API


=== Find calls
'''
Example how to find all calls sent or received by the user. Use "CampaignId=0" for the campaignId parameter to query for all
 calls sent through the POST /calls API.
[source,csharp]
    CallfireClient Client = new CallfireClient("api_login", "api_password");
    //No one parameter is required
    var request = new FindCallsRequest
    {
        States = new List<StateType> { StateType.FINISHED, StateType.READY },
        IntervalBegin = DateTime.UtcNow.AddMonths(-2),
        IntervalEnd = DateTime.UtcNow,
        Limit = 3
    };
    Page<Call> calls = Client.CallsApi.Find(request);
    Console.WriteLine("Calls: " + calls);

=== Send call
'''
Example how to use the /calls API to quickly send individual calls via default campaign. A verified Caller ID and
 sufficient credits are required to make a call.
[source,csharp]
    CallfireClient Client = new CallfireClient("api_login", "api_password");
    //Only "recipients" param required
    var recipient1 = new CallRecipient { ContactId = 463633187003, LiveMessage = "testMessage", TransferDigit = "1", TransferMessage = "transferTestMessage", TransferNumber = "14246525473" };
    var recipient2 = new CallRecipient { ContactId = 463633187003, LiveMessage = "testMessage", TransferDigit = "1", TransferMessageSoundId = 1, TransferNumber = "14246525473" };
        r1.setTransferMessage("transferTestMessage");
        //or you can use transfer sound id
        r1.setTransferMessageSoundId(1123123L);
        r1.setTransferNumber("14246525473");
        r1.setTransferDigit("1");


    var recipients = new List<CallRecipient> { recipient1, recipient2 };
    IList<Call> calls = Client.CallsApi.Send(recipients, null, "items(id,fromNumber,state)");
    Console.WriteLine("Calls: " + calls);

In case you want to send call via existing campaign provide campaign id as second parameter for send() method,
 see example below.
[source,csharp]
    CallfireClient Client = new CallfireClient("api_login", "api_password");
    //Only "recipients" param required
    var recipient1 = new CallRecipient { ContactId = 463633187003, LiveMessage = "testMessage" };
    var recipient2 = new CallRecipient { ContactId = 463633187003, LiveMessage = "testMessage" };
    var recipients = new List<CallRecipient> { recipient1, recipient2 };
    IList<Call> calls = Client.CallsApi.Send(recipients, 60000000003);
    Console.WriteLine("Calls: " + calls);

Also you can send call with some default parameters which will be used in case when recipient doesn't have that info specified,
 see example below:
[source,csharp]
    CallfireClient Client = new CallfireClient("api_login", "api_password");
    //Only "recipients" param required
    var recipient1 = new CallRecipient { ContactId = 463633187003, LiveMessage = "testMessage" };
    var recipient2 = new CallRecipient { ContactId = 463633187003, LiveMessage = "testMessage" };
    var recipients = new List<CallRecipient> { recipient1, recipient2 };
    var request = new SendCallsRequest
        {
            Recipients = recipients,
            CampaignId = 7373471003,
            Fields = "items(id, fromNumber, state, campaignId)",
            DefaultLiveMessage = "DefaultLiveMessage",
            DefaultMachineMessage = "DefaultMachineMessage",
            DefaultVoice = CallfireApiClient.Api.Campaigns.Model.Voice.FRENCHCANADIAN1
        };
    IList<Call> calls = Client.CallsApi.Send(request);
    request = new SendCallsRequest
        {
            Recipients = recipients,
            CampaignId = 7373471003,
            Fields = "items(id, fromNumber, state, campaignId)",
            DefaultLiveMessageSoundId = 1,
            DefaultMachineMessageSoundId = 1,
            DefaultVoice = CallfireApiClient.Api.Campaigns.Model.Voice.FRENCHCANADIAN1
        };
    calls = Client.CallsApi.Send(request);

=== Get call
'''
Example how to return a single Call instance for a given call id.
[source,csharp]
    //Only "id" param required
    CallfireClient Client = new CallfireClient("api_login", "api_password");
    Call call = Client.CallsApi.Get(617067920003, "id,toNumber,state");
    Console.WriteLine("Call: " + call);

=== Get call recordings
'''
Example how to return call recordings for a given call id.
[source,csharp]
    //Only "id" param required
    CallfireClient Client = new CallfireClient("api_login", "api_password");
    IList<CallRecording> recs = Client.CallsApi.GetCallRecordings(1234, "items(callId)");

=== Get call recording by name and call id
'''
Example how to return call recording for a given call by recording name.
[source,csharp]
    //"id" and "name" params are required
    CallfireClient Client = new CallfireClient("api_login", "api_password");
    CallRecording recording = Client.CallsApi.GetCallRecordingByName(1234, "testName", "callId");

=== Get mp3 call recording by name and call id
'''
Example how to return mp3 call recording for a given call by recording name.
[source,csharp]
    //"id" and "name" params are required
    CallfireClient Client = new CallfireClient("api_login", "api_password");
    MemoryStream ms = (MemoryStream)Client.CallsApi.GetCallRecordingMp3ByName(1234, "testName");

=== Get call recording by id
'''
Example how to return call recording for a given recording id.
[source,csharp]
    //Only "id" param required
    CallfireClient Client = new CallfireClient("api_login", "api_password");
    CallRecording rec = Client.CallsApi.GetCallRecording(1234, "campaignId");

=== Get mp3 call recording by id
'''
Example how to return mp3 call recording for a given recording id.
[source,csharp]
    //Only "id" param required
    CallfireClient Client = new CallfireClient("api_login", "api_password");
    MemoryStream ms = (MemoryStream)Client.CallsApi.GetCallRecordingMp3(1234);
