= Media API

=== Upload media file
'''
Example how to upload media file to account.
[source,csharp]
    CallfireClient Client = new CallfireClient("api_login", "api_password");
    String soundName = "mp3_file";
    ResourceId resourceId = Client.MediaApi.Upload(mp3FilePath, soundName);
    Console.WriteLine("Media file id: " + resourceId);

=== Get media
'''
Example how to get a single Media instance for a given media file id. This is the metadata
 for the media only. No content data is returned from this API.
[source,csharp]
    CallfireClient Client = new CallfireClient("api_login", "api_password");
    Media media = Client.MediaApi.Get(213421, "id,created");
    Console.WriteLine("Media file: " + media);

=== Get media file data
'''
Example how to get media file's data as stream.
[source,csharp]
    CallfireClient Client = new CallfireClient("api_login", "api_password");
    MemoryStream ms = (MemoryStream)Client.MediaApi.GetData(213234, MediaType.MP3);
    File.WriteAllBytes("Resources/File-examples/train.mp3", ms.ToArray());

Next code sample uses key parameter to get data.
[source,csharp]
    CallfireClient Client = new CallfireClient("api_login", "api_password");
    MemoryStream ms = (MemoryStream)Client.MediaApi.GetData("testKey", MediaType.MP3);
    File.WriteAllBytes("Resources/File-examples/train.mp3", ms.ToArray());
