= Text broadcasts API


=== Find broadcasts
Find all text broadcasts created by the user. Can query on label, name, and the current running status of
 the campaign. Returns a paged list of text broadcasts.
 Example how to find 2 text broadcasts which have 'campaign' suffix in their names:
[source,csharp]
    var client = new CallfireClient("api_login", "api_password");
    var request = new FindBroadcastsRequest
    {
        Name = "campaign name",
        Limit = 1
    };
    var broadcasts = client.TextBroadcastsApi.Find(request);
    Console.WriteLine(broadcasts);

=== Create broadcast
Example how to create text broadcast and then start it. Broadcast will send messages within allowed
 hours (10:10 - 22:00) to 2 recipients.
[source,csharp]
    var client = new CallfireClient("api_login", "api_password");
    var broadcast = new TextBroadcast
    {
        Name = "voice_broadcast",
        FromNumber = "12131234567",
        BigMessageStrategy = BigMessageStrategy.SEND_MULTIPLE,
        Message = "test_msg",
        LocalTimeRestriction = new LocalTimeRestriction
        {
            BeginHour = 10,
            BeginMinute = 10,
            EndHour = 22,
            EndMinute = 0,
            Enabled = true
        },
        Recipients = new List<TextRecipient>
        {
            new TextRecipient { PhoneNumber = "12132212384" },
            new TextRecipient { PhoneNumber = "12132212385" }
        },
        ResumeNextDay = true
    };
    // create broadcast
    var id = client.TextBroadcastsApi.Create(broadcast, true);

=== Get broadcast
Get text broadcast by ID.
[source,csharp]
    var client = new CallfireClient("api_login", "api_password");
    var broadcast = client.TextBroadcastsApi.Get(123L);
    Console.WriteLine(broadcast);

=== Update broadcast
After having created a text broadcast campaign, this method lets the user modify the configuration of
 a text broadcast campaign.
 See example how to update name of campaign:
[source,csharp]
    var client = new CallfireClient("api_login", "api_password");
    var broadcast = client.TextBroadcastsApi.Get(123L);
    broadcast.Name = "New name";
    // update campaign
    client.TextBroadcastsApi.Update(broadcast);

=== Start broadcast
Start text broadcast by ID.
[source,csharp]
    var client = new CallfireClient("api_login", "api_password");
    client.TextBroadcastsApi.Start(123L);

=== Stop broadcast
Stop text broadcast by ID.
[source,csharp]
    var client = new CallfireClient("api_login", "api_password");
    client.TextBroadcastsApi.Stop(123L);

=== Archive broadcast
Archive text broadcast by ID.
[source,csharp]
    var client = new CallfireClient("api_login", "api_password");
    client.TextBroadcastsApi.Archive(123L);

=== Get broadcast texts
This operation will enable the user to page through all of the texts for a particular text broadcast campaign.
[source,csharp]
    var client = new CallfireClient("api_login", "api_password");
    var request = new GetByIdRequest { Id = 123 };
    var texts = client.TextBroadcastsApi.GetTexts(request);
    Console.WriteLine(texts);

If you want to get texts filtered by batch id please use code like:
[source,csharp]
    var client = new CallfireClient("api_login", "api_password");
    var request = new GetBroadcastCallsTextsRequest { Id = 123, batchId = 1234 };
    var texts = client.TextBroadcastsApi.GetTexts(request);

=== Get broadcast stats
Get broadcast statistics.
[source,csharp]
    var client = new CallfireClient("api_login", "api_password");
    var begin = DateTime.Now.AddDays(-5d);
    var end = DateTime.Now;
    var stats = client.TextBroadcastsApi.GetStats(8624192003L, null, begin, end);
    Console.WriteLine(stats);

=== Add recipients to a text broadcast
Use this method to add recipients to an already created text broadcast. Post a list of Recipient objects for
 them to be immediately added to the text broadcast campaign. These contacts do not go through validation process,
 and will be acted upon as they are added. Recipients may be added as a list of contact ids, or list of numbers.
[source,csharp]
    CallfireClient client = new CallfireClient("api_login", "api_password");
    var recipients = new List<TextRecipient>
    {
        new TextRecipient { PhoneNumber = "12132212384" },
        new TextRecipient { PhoneNumber = "12132212385" }
    };
    var texts = client.TextBroadcastsApi.AddRecipients(1234, recipients);
    Console.WriteLine(texts);

=== Get a specific broadcast batch
Returns a single Batch instance for a given text broadcast batch id.
[source,csharp]
    CallfireClient client = new CallfireClient("api_login", "api_password");
    var getBatchRequest = new GetByIdRequest { Id = 1234 };
    Batch batch = client.TextBroadcastsApi.GetBatch(batchRequest);
    Console.WriteLine(batch);

=== Get all broadcast batches
This method will enable the user to page through all of the batches for a particular text broadcast campaign.
[source,csharp]
    CallfireClient client = new CallfireClient("api_login", "api_password");
    var getBatchesRequest = new GetByIdRequest { Id = 12345 };
    var batches = client.TextBroadcastsApi.GetBatches(getBatchesRequest);
    Console.WriteLine(batches);

=== Update a specific broadcast batch
Update a text broadcast batch. Can only change enabled at this time.
[source,csharp]
    CallfireClient client = new CallfireClient("api_login", "api_password");
    var getBatchRequest = new GetByIdRequest { Id = 1234 };
    Batch batch = client.TextBroadcastsApi.GetBatch(getBatchRequest);
    batch.Enabled = false;
    client.TextBroadcastsApi.UpdateBatch(batch);

=== Add batch to broadcast
The add batch method allows the user to add additional batches to an already created text broadcast campaign.
 The added batch will go through the CallFire validation process, unlike in the recipients version of this API.
 Because of this, use the scrubDuplicates flag to remove duplicates from your batch. Batches may be added as a
 contact list id, a list of contact ids, or a list of numbers.
[source,csharp]
    var client = new CallfireClient("api_login", "api_password");
    // add batch
    var addBatchRequest = new AddBatchRequest
    {
        CampaignId = (long)id,
        Name = "new_batch",
        Recipients = new List<Recipient>
        {
            new TextRecipient { PhoneNumber = "12132212384" },
            new TextRecipient { PhoneNumber = "12132212385" }
        }
    };
    var resourceId = Client.TextBroadcastsApi.AddBatch(addBatchRequest);
