= Webhooks API


=== Find webhooks
'''
Search for webhooks on name, resource, event, callback URL, or whether they are enabled.
 Example how to get first 5 webhooks which are *enabled* and assigned to resource *"textBroadcast"*.
[source,csharp]
    CallfireClient Client = new CallfireClient("api_login", "api_password");
    var findRequest = new FindWebhooksRequest
    {
        Limit = 5,
        Enabled = true,
        Name = "test_name"
    };
    Page<Webhook> webhooks = Client.WebhooksApi.Find(findRequest);
    Console.WriteLine(webhooks);

=== Get webhook
'''
Example how to get a single Webhook instance for a given webhook id.
[source,csharp]
    CallfireClient Client = new CallfireClient("api_login", "api_password");
    Webhook webhook = Client.WebhooksApi.Get(12345678, "id,name,created");
    Console.WriteLine("Webhook: " + webhook);

=== Create webhook
'''
Example how to create a webhook for voice campaign. Callfire will query your callback URL with http POST request when
 any campaign has STARTED or FINISHED.
[source,csharp]
    CallfireClient Client = new CallfireClient("api_login", "api_password");
    var webhook = new Webhook
    {
        Name = "new webhook",
        Resource = ResourceType.TEXT_BROADCAST,
        Events = new HashSet<ResourceEvent> { ResourceEvent.STARTED, ResourceEvent.FINISHED },
        Callback = "https://yoursite.com/callback"
    };
    ResourceId resource = Client.WebhooksApi.Create(webhook);
    Console.WriteLine(resource.Id);

=== Update webhook
'''
Example how to update the information in a currently existing webhook. Most fields are updatable.
[source,csharp]
    CallfireClient Client = new CallfireClient("api_login", "api_password");
    var webhook = new Webhook
    {
        Id = 12345678,
        Name = "new webhook",
        Resource = ResourceType.TEXT_BROADCAST,
        Events = new HashSet<ResourceEvent> { ResourceEvent.STARTED, ResourceEvent.FINISHED },
        Callback = "https://yoursite.com/callback"
    };
    Client.WebhooksApi.Update(webhook);

=== Delete webhook
'''
Example how to delete a webhook. Will be removed permenantly.
[source,csharp]
    CallfireClient Client = new CallfireClient("api_login", "api_password");
    Client.WebhooksApi.Delete(12345678);

=== Find webhook resources
'''
Example how to find webhook resources.
[source,csharp]
    CallfireClient Client = new CallfireClient("api_login", "api_password");
    var resources = Client.WebhooksApi.FindWebhookResources("items(resource)");

=== Find webhook resource
'''
Example how to find webhook resource.
[source,csharp]
    CallfireClient Client = new CallfireClient("api_login", "api_password");
    var resource = Client.WebhooksApi.FindWebhookResource(ResourceType.CALL_BROADCAST, "resource");
