= Numbers API


=== Find local numbers
'''
Example how to find numbers in the CallFire local numbers catalog that are available for purchase.
[source]
    CallfireClient Client = new CallfireClient("api_login", "api_password");
    //At least one parameter is required
    var request = new FindNumbersLocalRequest { Limit = 2, State = "LA" };
    IList<Number> numbers = Client.NumbersApi.FindNumbersLocal(request);
    Console.WriteLine(numbers);
    
=== Find number regions
'''
Use this API to obtain detailed region information that can then be used to query for more specific phone numbers
 than a general query. Example below shows how to find number region information for specified state and zip code.
[source]
    CallfireClient Client = new CallfireClient("api_login", "api_password");
    //At least one parameter is required
    var request = new FindNumberRegionsRequest
    {
        Limit = 2,
        State = "IL",
        Zipcode = "60640"
    };
    Page<Region> regions = Client.NumbersApi.FindNumberRegions(request);
    Console.WriteLine(regions);

=== Find numbers tollfree
'''
Example how to find numbers in the CallFire tollfree numbers catalog that are available for purchase.
[source]
    CallfireClient Client = new CallfireClient("api_login", "api_password");
    var request = new CommonFindRequest { Limit = 2, Offset = 1 };
    IList<Number> numbers = Client.NumbersApi.FindNumbersTollfree(request);
    Console.WriteLine(numbers);
